insert into enemies(enemy_id, enemy_name, health, damage_limit, defence, difficulty, gif, already_killed) values
    ('0', 'Goblin', 60, 10, 10, 'easy', 'enemies/Goblin_enemy.gif', 'false'),
    ('1', 'Sewer Rat', 65, 15, 0, 'easy', 'enemies/rat_enemy.gif', 'false'),
    ('2', 'Giant Spider', 50, 15, 15, 'easy', 'enemies/spider_enemy2.gif', 'false'),
    ('3', 'Orc', 75, 10, 5, 'easy', 'enemies/orc.gif', 'false'),
    ('4', 'Blade Smith', 85, 25, 10, 'medium', 'enemies/Samurai_enemy.gif', 'false'),
    ('5', 'Forest Bear', 100, 15, 5, 'medium', 'enemies/bear_enemy.gif', 'false'),
    ('6', 'Corrupt Shaman', 90, 20, 10, 'medium', 'enemies/shaman_enemy.gif', 'false'),
    ('7', 'Shadow Assassin', 80, 15, 25, 'medium', 'enemies/assassin_enemy.gif', 'false'),
    ('8', 'Elemental Wizard', 110, 30, 20, 'hard', 'enemies/wizard_enemy.gif', 'false'),
    ('9', 'Forgotten Paladin', 120, 10, 30, 'hard', 'enemies/fPaladin_enemy.gif', 'false'),
    ('10', 'Infernal Drake', 110, 25, 25, 'hard', 'enemies/drake_enemy.gif', 'false'),
    ('11', 'Tree ent', 100, 20, 40, 'hard', 'enemies/treeent_enemy.gif', 'false'),
    ('12', 'BOSS : Lich King', 245, 35, 30, 'boss', 'enemies/Lich_King.gif', 'false'),
    ('13', 'BOSS : Bone Master', 255, 20, 35, 'boss', 'enemies/Skeleton_master.gif', 'false'),
    ('14', 'BOSS : Dragon King', 230, 40, 30, 'boss', 'enemies/Dragon_king.gif', 'false');