insert into enemies(enemy_id, enemy_name, health, damage_limit, defence, difficulty, gif, already_killed) values
    ('0', 'Goblin', 50, 10, 10, 'easy', 'enemies/Goblin_enemy.gif', 'false'),
    ('1', 'Sewer Rat', 60, 10, 5, 'easy', 'enemies/rat_enemy.gif', 'false'),
    ('2', 'Giant Spider', 80, 12, 10, 'easy', 'enemies/spider_enemy2.gif', 'false'),
    ('3', 'Orc', 100, 10, 5, 'easy', 'enemies/orc.gif', 'false'),
    ('4', 'Blade Smith', 120, 15, 15, 'medium', 'enemies/Samurai_enemy.gif', 'false'),
    ('5', 'Forest Bear', 140, 20, 10, 'medium', 'enemies/bear_enemy.gif', 'false'),
    ('6', 'Corrupt Shaman', 115, 15, 10, 'medium', 'enemies/shaman_enemy.gif', 'false'),
    ('7', 'Shadow Assassin', 100, 25, 5, 'medium', 'enemies/assassin_enemy.gif', 'false'),
    ('8', 'Elemental Wizard', 150, 35, 15, 'hard', 'enemies/wizard_enemy.gif', 'false'),
    ('9', 'Forgotten Paladin', 180, 10, 30, 'hard', 'enemies/fPaladin_enemy.gif', 'false'),
    ('10', 'Infernal Drake', 160, 30, 20, 'hard', 'enemies/drake_enemy.gif', 'false'),
    ('11', 'Tree ent', 165, 25, 15, 'hard', 'enemies/treeent_enemy.gif', 'false'),
    ('12', 'BOSS : Lich King', 250, 45, 25, 'boss', 'enemies/Lich_King.gif', 'false'),
    ('13', 'BOSS : Titan', 300, 35, 20, 'boss', 'enemies/Titan_enemy.gif', 'false');